# -*- coding: utf-8 -*-
"""📊 Market Cluster Dashboard - Google Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7yGayUroOBjnvqcUGFzu9RqgWnbv8zx

Célula 1: Instalar Dependências
"""

# Instalar bibliotecas necessárias
!pip install -q yfinance pandas plotly

print("✓ Dependências instaladas com sucesso!")

"""🔧 Célula 2: Importar Bibliotecas e Configurar Clusters"""

import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import json
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# CONFIGURAÇÃO DOS CLUSTERS
# ============================================================================

CLUSTERS = {
    "1_ia_infraestrutura": {
        "nome": "Infraestrutura de IA & Super-Ciclo de Memória",
        "tese": "A aceleração da IA exige expansão física massiva de hardware e data centers.",
        "driver_principal": "Outlook de IA e backlog de pedidos bilionários",
        "proxy_narrativa": "Crescimento de capex em data centers e volume de pedidos de chips",
        "ativos": {
            "AMD": {"papel": "Alternativa de GPU", "proxy": "Market share em inferência"},
            "MU": {"papel": "Memória HBM", "proxy": "Super-ciclo de memória"},
            "VRT": {"papel": "Refrigeração", "proxy": "Infraestrutura de data centers"},
            "APLD": {"papel": "Hosting de Data Centers", "proxy": "Operação direta de infraestrutura"},
        },
    },

    "2_juros_desreg": {
        "nome": "Proxies de Juros & Desregulamentação US",
        "tese": "Normalização da política monetária beneficia o setor financeiro.",
        "driver_principal": "Ciclo de política monetária e força do mercado de trabalho",
        "proxy_narrativa": "Taxa de desemprego, decisões do Fed, volume de refinanciamentos",
        "ativos": {
            "ADP": {"papel": "Proxy de Emprego", "proxy": "Força do mercado de trabalho"},
            "JPM": {"papel": "Líder Bancário", "proxy": "Consolidação e desregulamentação"},
            "SOFI": {"papel": "Fintech Escalável", "proxy": "Expansão de margem"},
            "BLK": {"papel": "Fluxo de Capital", "proxy": "AUM em ciclo risco-on"},
        },
    },

    "3_defesa_moats": {
        "nome": "Defesa de Portfólio & Moats Inabaláveis",
        "tese": "Empresas com barreiras de entrada inabaláveis oferecem proteção.",
        "driver_principal": "Robustez vs. Macro e barreiras de entrada",
        "proxy_narrativa": "Pricing power, brand strength, consistência de dividendos",
        "ativos": {
            "BRK-B": {"papel": "Robustez Extrema", "proxy": "Caixa e diversificação"},
            "KO": {"papel": "Pricing Power", "proxy": "Força da marca global"},
            "PG": {"papel": "Consumo Essencial", "proxy": "Resiliência em recessões"},
            "AMZN": {"papel": "Moat de Rede", "proxy": "Domínio logístico e AWS"},
        },
    },

    "4_tarifas_commodities": {
        "nome": "Arbitragem de Tarifas & Commodities (Brasil)",
        "tese": "Tarifas US criam oportunidades de arbitragem e protegem empresas locais.",
        "driver_principal": "Tensões comerciais globais e eficiência local",
        "proxy_narrativa": "Volume de tarifas impostas, demanda chinesa, fluxo estrangeiro",
        "ativos": {
            "GGBR4.SA": {"papel": "Siderurgia Local", "proxy": "Proteção de mercado"},
            "VALE3.SA": {"papel": "Custo de Produção", "proxy": "Qualidade e eficiência"},
            "WEGE3.SA": {"papel": "Eficiência Global", "proxy": "Exposição cambial"},
            "EWZ": {"papel": "Fluxo Estrangeiro", "proxy": "Apetite de risco em EM"},
        },
    },

    "5_quantum_seguranca": {
        "nome": "Computação Quântica & Cibersegurança Pós-Quântica",
        "tese": "Computação quântica atingiu maturidade comercial.",
        "driver_principal": "Maturidade comercial de qubits e compliance de segurança",
        "proxy_narrativa": "Roadmap de qubits, parcerias industriais, contratos de compliance",
        "ativos": {
            "IONQ": {"papel": "Hardware Quântico", "proxy": "Roadmap de 256 qubits"},
            "QBTS": {"papel": "Computação de Recozimento", "proxy": "Otimização comercial"},
            "RGTI": {"papel": "Sistemas Full-Stack", "proxy": "Integração hardware-software"},
            "CRWD": {"papel": "Defesa Digital PQC", "proxy": "Adaptação de protocolos"},
        },
    },

    "6_defesa_autonoma": {
        "nome": "Defesa Autônoma & Sistemas de Drones",
        "tese": "Doutrina militar mudou para sistemas autônomos.",
        "driver_principal": "Mudança doutrinária militar e eficiência de custos",
        "proxy_narrativa": "Contratos militares, volume de conflitos, adoção de drones",
        "ativos": {
            "AVAV": {"papel": "Drones Táticos", "proxy": "Liderança em sistemas não tripulados"},
            "KTOS": {"papel": "Alvos e Drones", "proxy": "Drones de baixo custo"},
            "EH": {"papel": "Mobilidade Aérea", "proxy": "Expansão de logística autônoma"},
            "PLTR": {"papel": "Software de Combate", "proxy": "Coordenação de sistemas autônomos"},
        },
    },

    "7_cripto_infraestrutura": {
        "nome": "Cripto-Infraestrutura & Alavancagem Operacional",
        "tese": "Melhor trade em cripto é via alavancagem operacional.",
        "driver_principal": "Alavancagem operacional e convergência com IA",
        "proxy_narrativa": "Preço do BTC, volume de mineração, contratos de energia",
        "ativos": {
            "MSTR": {"papel": "Proxy de Bitcoin", "proxy": "Alavancagem financeira extrema"},
            "COIN": {"papel": "Infraestrutura de Troca", "proxy": "Volume de negociação"},
            "MARA": {"papel": "Mineração Verticalizada", "proxy": "Eficiência operacional"},
            "RIOT": {"papel": "Escala de Mineração", "proxy": "Expansão de hash rate"},
        },
    },
}

print("✓ Clusters configurados!")

"""📊 Célula 3: Função para Buscar Dados de Mercado"""

def fetch_market_data(verbose=True):
    """Busca dados de mercado para todos os ativos"""
    all_data = {}

    for cluster_id, cluster_info in CLUSTERS.items():
        if verbose:
            print(f"📊 Buscando {cluster_info['nome']}...")

        cluster_data = {
            "cluster_id": cluster_id,
            "nome": cluster_info["nome"],
            "tese": cluster_info["tese"],
            "driver_principal": cluster_info["driver_principal"],
            "proxy_narrativa": cluster_info["proxy_narrativa"],
            "ativos": {},
            "timestamp": datetime.now().isoformat(),
        }

        for ticker, ativo_info in cluster_info["ativos"].items():
            try:
                dados = yf.Ticker(ticker)
                hist = dados.history(period="1d")

                if not hist.empty:
                    preco_atual = hist["Close"].iloc[-1]
                    volume = hist["Volume"].iloc[-1]

                    hist_30d = dados.history(period="30d")
                    preco_30d_atras = hist_30d["Close"].iloc[0] if len(hist_30d) > 0 else preco_atual
                    variacao_30d = ((preco_atual - preco_30d_atras) / preco_30d_atras * 100) if preco_30d_atras != 0 else 0

                    cluster_data["ativos"][ticker] = {
                        "preco": round(preco_atual, 2),
                        "volume": int(volume),
                        "variacao_30d_pct": round(variacao_30d, 2),
                        "papel": ativo_info["papel"],
                        "proxy": ativo_info["proxy"],
                        "timestamp": datetime.now().isoformat(),
                    }

                    if verbose:
                        print(f"  ✓ {ticker}: ${preco_atual:.2f} ({variacao_30d:+.2f}%)")
                else:
                    if verbose:
                        print(f"  ⚠ {ticker}: Sem dados")

            except Exception as e:
                if verbose:
                    print(f"  ✗ {ticker}: Erro")

        all_data[cluster_id] = cluster_data

    return all_data

print("✓ Função de coleta de dados criada!")

"""🔄 Célula 4: Buscar Dados (Executar Isto!)"""

print("⏳ Buscando dados de mercado... (pode levar 1-2 minutos)")
cluster_data = fetch_market_data(verbose=True)
print("\n✓ Dados coletados com sucesso!")

"""📈 Célula 5: Gráfico 1 - Performance dos Clusters"""

# Preparar dados
cluster_performance = []

for cluster_id, cluster_info in cluster_data.items():
    variacao_media = sum([a["variacao_30d_pct"] for a in cluster_info["ativos"].values()]) / len(cluster_info["ativos"]) if cluster_info["ativos"] else 0
    cluster_performance.append({
        "Cluster": cluster_info["nome"][:25],
        "Variação Média %": variacao_media
    })

df_performance = pd.DataFrame(cluster_performance)

# Criar gráfico
fig = px.bar(df_performance, x="Cluster", y="Variação Média %",
             color="Variação Média %",
             color_continuous_scale="RdYlGn",
             title="📊 Performance Média dos Clusters (30 dias)",
             height=500)

fig.update_layout(xaxis_tickangle=-45, template="plotly_white")
fig.show()

"""🔥 Célula 6: Gráfico 2 - Heatmap de Performance"""

# Preparar dados para heatmap
heatmap_data = []

for cluster_id, cluster_info in cluster_data.items():
    for ticker, ativo_data in cluster_info["ativos"].items():
        heatmap_data.append({
            "Cluster": cluster_info["nome"][:20],
            "Ticker": ticker,
            "Variação %": ativo_data["variacao_30d_pct"]
        })

df_heatmap = pd.DataFrame(heatmap_data)
pivot_df = df_heatmap.pivot_table(values="Variação %", index="Ticker", columns="Cluster", fill_value=0)

# Criar heatmap
fig = go.Figure(data=go.Heatmap(
    z=pivot_df.values,
    x=pivot_df.columns,
    y=pivot_df.index,
    colorscale="RdYlGn",
    zmid=0,
    colorbar=dict(title="Variação %")
))

fig.update_layout(
    title="🔥 Heatmap de Performance - Todos os Clusters",
    height=600,
    template="plotly_white"
)

fig.show()

"""📋 Célula 7: Tabela de Resumo"""

# Criar tabela de resumo
summary_data = []

for cluster_id, cluster_info in cluster_data.items():
    variacao_media = sum([a["variacao_30d_pct"] for a in cluster_info["ativos"].values()]) / len(cluster_info["ativos"]) if cluster_info["ativos"] else 0

    summary_data.append({
        "Cluster": cluster_info["nome"],
        "Ativos": len(cluster_info["ativos"]),
        "Variação Média (%)": f"{variacao_media:+.2f}%",
        "Driver": cluster_info["driver_principal"][:50]
    })

df_summary = pd.DataFrame(summary_data)

# Exibir como tabela
print("\n" + "="*120)
print("📋 RESUMO DE TODOS OS CLUSTERS")
print("="*120)
print(df_summary.to_string(index=False))
print("="*120)

"""🔍 Célula 8: Detalhes de um Cluster Específico"""

# Selecionar um cluster para análise detalhada
cluster_id = "1_ia_infraestrutura"  # Mude este ID para ver outro cluster
cluster = cluster_data[cluster_id]

print(f"\n📌 {cluster['nome']}")
print(f"Tese: {cluster['tese']}")
print(f"Driver: {cluster['driver_principal']}")
print(f"Proxy: {cluster['proxy_narrativa']}\n")

# Criar tabela de ativos
ativos_list = []
for ticker, ativo_data in cluster["ativos"].items():
    ativos_list.append({
        "Ticker": ticker,
        "Preço": f"${ativo_data['preco']:.2f}",
        "Variação 30d (%)": f"{ativo_data['variacao_30d_pct']:+.2f}%",
        "Papel": ativo_data["papel"],
        "Proxy": ativo_data["proxy"],
    })

df_ativos = pd.DataFrame(ativos_list)
print(df_ativos.to_string(index=False))

# Gráfico de variação
chart_data = []
for ticker, ativo_data in cluster["ativos"].items():
    chart_data.append({
        "Ticker": ticker,
        "Variação %": ativo_data["variacao_30d_pct"]
    })

df_chart = pd.DataFrame(chart_data)
fig = px.bar(df_chart, x="Ticker", y="Variação %",
             color="Variação %",
             color_continuous_scale="RdYlGn",
             title=f"📈 {cluster['nome']} - Variação de Preço (30 dias)",
             height=400)

fig.update_layout(template="plotly_white")
fig.show()

"""💾 Célula 9: Exportar Dados para CSV"""

# Exportar dados para CSV
df_summary.to_csv("cluster_summary.csv", index=False)
print("✓ Dados exportados para 'cluster_summary.csv'")

# Exportar dados completos em JSON
import json
with open("cluster_data.json", "w") as f:
    json.dump(cluster_data, f, indent=2)
print("✓ Dados completos exportados para 'cluster_data.json'")

# Você pode fazer download desses arquivos do Colab

"""🔄 Célula 10: Atualizar Dados (Executar Periodicamente)"""

# Para atualizar os dados a qualquer momento, execute:
print("⏳ Atualizando dados...")
cluster_data = fetch_market_data(verbose=False)
print("✓ Dados atualizados!")

# Depois execute novamente as células de gráficos para ver os dados atualizados